package com.draco.buoy.repositories.constants

object BatterySaverConstants31 {
    const val ADVERTISE_IS_ENABLED =        "advertise_is_enabled"
    const val DATASAVER_DISABLED =          "datasaver_disabled"
    const val ENABLE_NIGHT_MODE =           "enable_night_mode"
    const val LAUNCH_BOOST_DISABLED =       "launch_boost_disabled"
    const val VIBRATION_DISABLED =          "vibration_disabled"
    const val ANIMATION_DISABLED =          "animation_disabled"
    const val SOUNDTRIGGER_DISABLED =       "soundtrigger_disabled"
    const val FULLBACKUP_DEFERRED =         "fullbackup_deferred"
    const val KEYVALUEBACKUP_DEFERRED =     "keyvaluebackup_deferred"
    const val FIREWALL_DISABLED =           "firewall_disabled"
    const val GPS_MODE =                    "gps_mode"
    const val ADJUST_BRIGHTNESS_DISABLED =  "adjust_brightness_disabled"
    const val ADJUST_BRIGHTNESS_FACTOR =    "adjust_brightness_factor"
    const val FORCE_ALL_APPS_STANDBY =      "force_all_apps_standby"
    const val FORCE_BACKGROUND_CHECK =      "force_background_check"
    const val OPTIONAL_SENSORS_DISABLED =   "optional_sensors_disabled"
    const val AOD_DISABLED =                "aod_disabled"
    const val QUICK_DOZE_ENABLED =          "quick_doze_enabled"
}

object BatterySaverConstants32 {
    const val ADVERTISE_IS_ENABLED =         "advertise_is_enabled"
    const val ENABLE_DATASAVER =             "enable_datasaver"
    const val ENABLE_NIGHT_MODE =            "enable_night_mode"
    const val DISABLE_LAUNCH_BOOST =         "disable_launch_boost"
    const val DISABLE_VIBRATION =            "disable_vibration"
    const val DISABLE_ANIMATION =            "disable_animation"
    const val DISABLE_SOUNDTRIGGER =         "disable_soundtrigger"
    const val DEFER_FULL_BACKUP =            "defer_full_backup"
    const val DEFER_KEYVALUE_BACKUP =        "defer_keyvalue_backup"
    const val ENABLE_FIREWALL =              "enable_firewall"
    const val LOCATION_MODE =                "location_mode"
    const val ENABLE_BRIGHTNESS_ADJUSTMENT = "enable_brightness_adjustment"
    const val ADJUST_BRIGHTNESS_FACTOR =     "adjust_brightness_factor"
    const val FORCE_ALL_APPS_STANDBY =       "force_all_apps_standby"
    const val FORCE_BACKGROUND_CHECK =       "force_background_check"
    const val DISABLE_OPTIONAL_SENSORS =     "disable_optional_sensors"
    const val DISABLE_AOD =                  "disable_aod"
    const val ENABLE_QUICK_DOZE =            "enable_quick_doze"
}
